# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: (.Net)Restore dependencies
        run: dotnet restore
      - name: (.Net)Build
        run: dotnet build --no-restore --configuration Release
      - name: (.Net)Test
        run: dotnet test --no-build --verbosity normal

      - name: (.Net)Pack
        run: |
          dotnet pack \
            --configuration Release \
            --output ./Output \
            ./shmtu-dotnet-lib/shmtu-dotnet-lib.csproj

      - name: (.Net)Publish
        run: |
          export NUGET_API_KEY=${{ secrets.NUGET_API_KEY }}
          python ./Scripts/push_nuget.py
